// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processor_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CPU struct {
	// Brand of the CPU
	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	//
	// Name of the CPU
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NumberCores          uint32   `protobuf:"varint,3,opt,name=number_cores,json=numberCores,proto3" json:"number_cores,omitempty"`
	NumberThreads        uint32   `protobuf:"varint,4,opt,name=number_threads,json=numberThreads,proto3" json:"number_threads,omitempty"`
	MinGhz               float64  `protobuf:"fixed64,5,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz               float64  `protobuf:"fixed64,6,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}
func (*CPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_466578cecc6db379, []int{0}
}

func (m *CPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPU.Unmarshal(m, b)
}
func (m *CPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPU.Marshal(b, m, deterministic)
}
func (m *CPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPU.Merge(m, src)
}
func (m *CPU) XXX_Size() int {
	return xxx_messageInfo_CPU.Size(m)
}
func (m *CPU) XXX_DiscardUnknown() {
	xxx_messageInfo_CPU.DiscardUnknown(m)
}

var xxx_messageInfo_CPU proto.InternalMessageInfo

func (m *CPU) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *CPU) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CPU) GetNumberCores() uint32 {
	if m != nil {
		return m.NumberCores
	}
	return 0
}

func (m *CPU) GetNumberThreads() uint32 {
	if m != nil {
		return m.NumberThreads
	}
	return 0
}

func (m *CPU) GetMinGhz() float64 {
	if m != nil {
		return m.MinGhz
	}
	return 0
}

func (m *CPU) GetMaxGhz() float64 {
	if m != nil {
		return m.MaxGhz
	}
	return 0
}

type GPU struct {
	Brand                string   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MinGhz               float64  `protobuf:"fixed64,3,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz               float64  `protobuf:"fixed64,4,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	Memory               *Memory  `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPU) Reset()         { *m = GPU{} }
func (m *GPU) String() string { return proto.CompactTextString(m) }
func (*GPU) ProtoMessage()    {}
func (*GPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_466578cecc6db379, []int{1}
}

func (m *GPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPU.Unmarshal(m, b)
}
func (m *GPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPU.Marshal(b, m, deterministic)
}
func (m *GPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPU.Merge(m, src)
}
func (m *GPU) XXX_Size() int {
	return xxx_messageInfo_GPU.Size(m)
}
func (m *GPU) XXX_DiscardUnknown() {
	xxx_messageInfo_GPU.DiscardUnknown(m)
}

var xxx_messageInfo_GPU proto.InternalMessageInfo

func (m *GPU) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *GPU) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GPU) GetMinGhz() float64 {
	if m != nil {
		return m.MinGhz
	}
	return 0
}

func (m *GPU) GetMaxGhz() float64 {
	if m != nil {
		return m.MaxGhz
	}
	return 0
}

func (m *GPU) GetMemory() *Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func init() {
	proto.RegisterType((*CPU)(nil), "pcbook.CPU")
	proto.RegisterType((*GPU)(nil), "pcbook.GPU")
}

func init() { proto.RegisterFile("processor_message.proto", fileDescriptor_466578cecc6db379) }

var fileDescriptor_466578cecc6db379 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xc9, 0xb4, 0x13, 0xf1, 0x8e, 0x33, 0x8b, 0x50, 0x98, 0x20, 0x2e, 0xea, 0x80, 0xd2,
	0x55, 0x17, 0xfa, 0x06, 0xce, 0xa2, 0x2b, 0x61, 0x28, 0xba, 0x71, 0x53, 0x92, 0x36, 0x4c, 0x8a,
	0xe4, 0x87, 0xa4, 0xc2, 0xd8, 0x37, 0xf0, 0x59, 0x7c, 0x49, 0x31, 0xa9, 0x50, 0x17, 0x2e, 0xdc,
	0x25, 0xdf, 0x77, 0xe0, 0x5c, 0x0e, 0x6c, 0xad, 0x33, 0xad, 0xf0, 0xde, 0xb8, 0x46, 0x09, 0xef,
	0xd9, 0x51, 0x94, 0xd6, 0x99, 0xc1, 0x10, 0x6c, 0x5b, 0x6e, 0xcc, 0xeb, 0x65, 0xa6, 0x84, 0x32,
	0xee, 0xfd, 0xb7, 0xdd, 0x7d, 0x22, 0x48, 0xf6, 0x87, 0x67, 0x92, 0xc1, 0x92, 0x3b, 0xa6, 0x3b,
	0x8a, 0x72, 0x54, 0x9c, 0xd7, 0xf1, 0x43, 0x08, 0xa4, 0x9a, 0x29, 0x41, 0x17, 0x01, 0x86, 0x37,
	0xb9, 0x86, 0x0b, 0xfd, 0xa6, 0xb8, 0x70, 0x4d, 0x6b, 0x9c, 0xf0, 0x34, 0xc9, 0x51, 0xb1, 0xae,
	0x57, 0x91, 0xed, 0xbf, 0x11, 0xb9, 0x81, 0xcd, 0x14, 0x19, 0xa4, 0x13, 0xac, 0xf3, 0x34, 0x0d,
	0xa1, 0x75, 0xa4, 0x4f, 0x11, 0x92, 0x2d, 0x9c, 0xa9, 0x5e, 0x37, 0x47, 0x39, 0xd2, 0x65, 0x8e,
	0x0a, 0x54, 0x63, 0xd5, 0xeb, 0x4a, 0x8e, 0x41, 0xb0, 0x53, 0x10, 0x78, 0x12, 0xec, 0x54, 0xc9,
	0x71, 0xf7, 0x81, 0x20, 0xa9, 0xfe, 0x75, 0xed, 0xac, 0x23, 0xf9, 0xab, 0x23, 0x9d, 0x77, 0x90,
	0x5b, 0xc0, 0x71, 0xa9, 0x70, 0xd4, 0xea, 0x6e, 0x53, 0xc6, 0x01, 0xcb, 0xc7, 0x40, 0xeb, 0xc9,
	0x3e, 0x5c, 0x41, 0xd6, 0x1a, 0x55, 0x76, 0x03, 0xef, 0xb5, 0xfc, 0xc9, 0x58, 0x7e, 0x40, 0x2f,
	0x0b, 0xcb, 0x39, 0x0e, 0xf3, 0xde, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x14, 0x1f, 0x1b, 0x34,
	0x97, 0x01, 0x00, 0x00,
}
