// Code generated by protoc-gen-go. DO NOT EDIT.
// source: screen_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Screen_Panel int32

const (
	Screen_UNKNOWN Screen_Panel = 0
	Screen_IPS     Screen_Panel = 1
	Screen_OLED    Screen_Panel = 2
)

var Screen_Panel_name = map[int32]string{
	0: "UNKNOWN",
	1: "IPS",
	2: "OLED",
}

var Screen_Panel_value = map[string]int32{
	"UNKNOWN": 0,
	"IPS":     1,
	"OLED":    2,
}

func (x Screen_Panel) String() string {
	return proto.EnumName(Screen_Panel_name, int32(x))
}

func (Screen_Panel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a2814cd02b8aba7, []int{0, 0}
}

type Screen struct {
	SizeInch             float32            `protobuf:"fixed32,1,opt,name=size_inch,json=sizeInch,proto3" json:"size_inch,omitempty"`
	Resolution           *Screen_Resolution `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Panel                Screen_Panel       `protobuf:"varint,3,opt,name=panel,proto3,enum=techschool.pcbook.Screen_Panel" json:"panel,omitempty"`
	Multitouch           bool               `protobuf:"varint,4,opt,name=multitouch,proto3" json:"multitouch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Screen) Reset()         { *m = Screen{} }
func (m *Screen) String() string { return proto.CompactTextString(m) }
func (*Screen) ProtoMessage()    {}
func (*Screen) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2814cd02b8aba7, []int{0}
}

func (m *Screen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Screen.Unmarshal(m, b)
}
func (m *Screen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Screen.Marshal(b, m, deterministic)
}
func (m *Screen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Screen.Merge(m, src)
}
func (m *Screen) XXX_Size() int {
	return xxx_messageInfo_Screen.Size(m)
}
func (m *Screen) XXX_DiscardUnknown() {
	xxx_messageInfo_Screen.DiscardUnknown(m)
}

var xxx_messageInfo_Screen proto.InternalMessageInfo

func (m *Screen) GetSizeInch() float32 {
	if m != nil {
		return m.SizeInch
	}
	return 0
}

func (m *Screen) GetResolution() *Screen_Resolution {
	if m != nil {
		return m.Resolution
	}
	return nil
}

func (m *Screen) GetPanel() Screen_Panel {
	if m != nil {
		return m.Panel
	}
	return Screen_UNKNOWN
}

func (m *Screen) GetMultitouch() bool {
	if m != nil {
		return m.Multitouch
	}
	return false
}

type Screen_Resolution struct {
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Screen_Resolution) Reset()         { *m = Screen_Resolution{} }
func (m *Screen_Resolution) String() string { return proto.CompactTextString(m) }
func (*Screen_Resolution) ProtoMessage()    {}
func (*Screen_Resolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2814cd02b8aba7, []int{0, 0}
}

func (m *Screen_Resolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Screen_Resolution.Unmarshal(m, b)
}
func (m *Screen_Resolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Screen_Resolution.Marshal(b, m, deterministic)
}
func (m *Screen_Resolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Screen_Resolution.Merge(m, src)
}
func (m *Screen_Resolution) XXX_Size() int {
	return xxx_messageInfo_Screen_Resolution.Size(m)
}
func (m *Screen_Resolution) XXX_DiscardUnknown() {
	xxx_messageInfo_Screen_Resolution.DiscardUnknown(m)
}

var xxx_messageInfo_Screen_Resolution proto.InternalMessageInfo

func (m *Screen_Resolution) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Screen_Resolution) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("techschool.pcbook.Screen_Panel", Screen_Panel_name, Screen_Panel_value)
	proto.RegisterType((*Screen)(nil), "techschool.pcbook.Screen")
	proto.RegisterType((*Screen_Resolution)(nil), "techschool.pcbook.Screen.Resolution")
}

func init() { proto.RegisterFile("screen_message.proto", fileDescriptor_8a2814cd02b8aba7) }

var fileDescriptor_8a2814cd02b8aba7 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x4d, 0xb7, 0x75, 0xf5, 0x3f, 0x26, 0x35, 0x0c, 0x29, 0x0a, 0xae, 0x0c, 0x61, 0x3d,
	0xe5, 0x30, 0xf1, 0xe2, 0x51, 0xe6, 0x61, 0x28, 0x5d, 0xc9, 0x10, 0xc1, 0xcb, 0x58, 0xb3, 0xb0,
	0x04, 0xdb, 0x24, 0x34, 0x29, 0x82, 0x5f, 0xc8, 0xaf, 0x29, 0x6b, 0x45, 0x07, 0xea, 0xf1, 0x3d,
	0x7e, 0x79, 0xef, 0xe5, 0x0f, 0x23, 0xcb, 0x2a, 0xce, 0xd5, 0xba, 0xe4, 0xd6, 0x6e, 0x76, 0x9c,
	0x98, 0x4a, 0x3b, 0x8d, 0x4f, 0x1d, 0x67, 0xc2, 0x32, 0xa1, 0x75, 0x41, 0x0c, 0xcb, 0xb5, 0x7e,
	0x9d, 0x7c, 0x78, 0xe0, 0xaf, 0x1a, 0x16, 0x5f, 0xc0, 0xb1, 0x95, 0xef, 0x7c, 0x2d, 0x15, 0x13,
	0x11, 0x8a, 0x51, 0xe2, 0xd1, 0x60, 0x6f, 0x2c, 0x14, 0x13, 0x78, 0x0e, 0x50, 0x71, 0xab, 0x8b,
	0xda, 0x49, 0xad, 0x22, 0x2f, 0x46, 0xc9, 0x60, 0x76, 0x45, 0x7e, 0xe5, 0x91, 0x36, 0x8b, 0xd0,
	0x6f, 0x96, 0x1e, 0xbc, 0xc3, 0x37, 0xd0, 0x33, 0x1b, 0xc5, 0x8b, 0xa8, 0x13, 0xa3, 0xe4, 0x64,
	0x36, 0xfe, 0x3f, 0x20, 0xdb, 0x63, 0xb4, 0xa5, 0xf1, 0x25, 0x40, 0x59, 0x17, 0x4e, 0x3a, 0x5d,
	0x33, 0x11, 0x75, 0x63, 0x94, 0x04, 0xf4, 0xc0, 0x39, 0xbf, 0x05, 0xf8, 0x29, 0xc4, 0x23, 0xe8,
	0xbd, 0xc9, 0xad, 0x6b, 0xff, 0x30, 0xa4, 0xad, 0xc0, 0x67, 0xe0, 0x0b, 0x2e, 0x77, 0xc2, 0x35,
	0xe3, 0x87, 0xf4, 0x4b, 0x4d, 0xa6, 0xd0, 0x6b, 0xba, 0xf0, 0x00, 0xfa, 0x4f, 0xe9, 0x43, 0xba,
	0x7c, 0x4e, 0xc3, 0x23, 0xdc, 0x87, 0xce, 0x22, 0x5b, 0x85, 0x08, 0x07, 0xd0, 0x5d, 0x3e, 0xde,
	0xcf, 0x43, 0xef, 0x6e, 0x0a, 0x63, 0xa6, 0x4b, 0xb2, 0x75, 0xb9, 0x54, 0xe2, 0x8f, 0xe1, 0x26,
	0xcf, 0xd0, 0x8b, 0x67, 0xf2, 0xdc, 0x6f, 0x8e, 0x7d, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xd7,
	0x9d, 0x17, 0x5e, 0x84, 0x01, 0x00, 0x00,
}
